site_name: EgyTech_API

theme:
  name: material
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  icon:
    repo: fontawesome/brands/github

repo_url: https://github.com/Abdulrahman-Mustafa-Abdulrahman/egytech-api

plugins:
  - mkdocstrings
  - search

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

nav:
  - Home: "index.md"
  - Classes:
      - Participants: "classes/participants.md"
      - Stats: "classes/stats.md"
      - PoolingClient: "classes/pooling-client.md"
      - AsyncPoolingClient: "classes/async-pooling-client.md"
      - ParticipantsQueryParams: "classes/participants-query-params.md"
      - StatsQueryParams: "classes/stats-query-params.md"
  - Examples:
      - "Using The Pooling Client": "examples/using-the-pooling-client.md"
  - About:
      - License: "license.md"
