name: docs_deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: pip install mkdocs-material mkdocstrings[python]
      - run: python -c "import os; print(os.listdir())"
      - run: mkdocs gh-deploy --force -f mkdocs.yml
